apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}}-service"
  namespace: "{{ .Values.service.namespace }}"
  labels:
    app: "{{ .Values.service.name }}}-app"
    release: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Values.service.name }}}-app"
    release: "{{ .Release.Name }}"
  ports:
    - name: http
      port: "{{ .Values.service.externalPort }}"
      targetPort: "{{ .Values.service.internalPort }}"
