replicaCount: 1
revisionHistoryLimit: 0
minReadySeconds: 10
maxUnavailable: 50%
maxSurge: 1
gracePeriod: 30

db:
    host: "localhost"
    name: "Lots"
    user: root
    password: root

image:
    name: peakle/goszakupki-parser
    tag: latest

service:
    name: lot
    host: goszakupki-parser.net
    namespace: default
    type: ClusterIP
    externalPort: "80"
    internalPort: "80"

resources:
    limits:
        cpu: 30m
        memory: 48Mi
    requests:
        cpu: 30m
        memory: 48Mi
